import ProjectDescription

let workspace = Workspace(
    name: "MateList",
    projects: [
        "Projects/Application",
        "Projects/Feat",
        "Projects/FeatNickName",
        "Projects/FeatDetail",
        "Projects/FeatScrap",
        "Projects/FeatSetting",
        "Projects/FeatSurvey",
        "Projects/Core",
        "Projects/Network",
        "Projects/Utility"
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: true,
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .relevant
        )
    )
)
